# node_Rod.sub

#-----------------------------------------------------------------------------
set: NoDyn_RodElem_curr = (NoDyn_RodElem_1st-1)+Index;

structural: NoDyn_RodElem_curr, dynamic,
   (Index-1)*L_RodElem, 0., 0., # absolute position
   eye,                         # absolute orientation
   null,                        # absolute velocity
   null;                        # absolute angular velocity